2020-12-02 16:41:43 | INFO      | ostDriver:ost_collection_modifyitems:35 - test_DLZC1
2020-12-02 16:41:43 | INFO      | ostDriver:ost_collection_modifyitems:37 - TestCases/Login/test_loginPageCase.py::TestLoginPageCase::test_DLZC1
2020-12-02 16:41:43 | INFO      | ostDriver:ost_collection_modifyitems:35 - test_DLZC7
2020-12-02 16:41:43 | INFO      | ostDriver:ost_collection_modifyitems:37 - TestCases/Register/test_registerPageCase.py::Test_RegisterPageCase::test_DLZC7
2020-12-02 16:41:43 | INFO      | ostDriver:ost_driver:63 - Get command line parameters:chrome
2020-12-02 16:41:44 | INFO      | remote_connection:__init__:116 - Could not connect to port 4444 on host 127.0.0.1
2020-12-02 16:41:44 | INFO      | remote_connection:__init__:135 - Could not get IP address for host: 127.0.0.1
2020-12-02 16:41:46 | WARNING      | connectionpool:urlopen:751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000189CEF6C460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-02 16:41:48 | WARNING      | connectionpool:urlopen:751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000189CEF6C5E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-02 16:41:50 | WARNING      | connectionpool:urlopen:751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000189CEF6C760>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-02 16:41:52 | INFO      | ostDriver:ost_driver:63 - Get command line parameters:chrome
